### ISSUE TITLE
Untested branch in addition.hpp

### ISSUE THREAD

**Issue by JohanEngelen** [niekbouman/ctbignum#10]
Branch at this spot is not tested:
https://github.com/niekbouman/finitefield/blob/f0781afea43a5d05858fb1e22ea3c409a3f72e6b/include/ctbignum/addition.hpp#L72

I.e., replacing with `if(true)` passes all tests.

**Comment by niekbouman** [comment]
Indeed, most unit tests currently have limited coverage.

However, for addition, there is now a SAW/cryptol-based formal correctness proof (proving equivalence between the addition implementation and a high-level specification of addition, which we assume to be correct). The user has to manually choose the input size, i.e., the equivalence proof then holds for that particular input size (it cannot yet prove equivalence *for all* input sizes at once).

Having this correctness proof makes unit tests for the addition function somewhat redundant. (One could also think of this correctness proof as the ultimate unit test.)

Next step would be to integrate the SAW prover into the build system. (For the addition function, the correctness proof takes only a couple of seconds.)
