### ISSUE TITLE
Inline attribute should be configurable

### ISSUE THREAD

**Issue by JohanEngelen** [niekbouman/ctbignum#29]
The always inline attribute should be a macro such that it can be configured (if the compiler does not support the particular way of enforcing inlining). For example:
https://github.com/niekbouman/ctbignum/blob/d1b26593ff96503fe447342c6555be3c831ed791/include/ctbignum/mult.hpp#L30

`#define CBN_ALWAYS_INLINE [[gnu::always_inline]` somewhere in a, e.g., `ctbignum/config.hpp` file.
Then later more fancy stuff can be added there for other compilers when needed.

**Comment by niekbouman** [comment]
added in [#31](https://github.com/niekbouman/ctbignum/pull/31)
