### ISSUE TITLE
Wrong value for mod_inv

### ISSUE THREAD

**Issue by juanmera** [niekbouman/ctbignum#46]
I was playing with the library and I found an issue with mod_inv. You can check it with the following code:
```cpp
auto p = cbn::to_big_int(115792089237316195423570985008687907853269984665640564039457584007908834671663_Z);
auto a = cbn::to_big_int(65341020041517633956166170261014086368942546761318486551877808671514674964848_Z);
std::cout << cbn::mod_inv(a, p) << std::endl;
```
It gives `83174505189910067536517124096019359197644205712500122884473429251816423926391` when it should be `83174505189910067536517124096019359197644205712500122884473429251812128958118`

The problem seems to be the negative numbers after calling to **subtract_ignore_carry**. There is a check at the end of the function for `t > modulus` but it doesn't apply to this case.

Tracking the signs of t and newt, and applying **add_ignore_carry** based on them works, but it is an ugly workaround:
```cpp
template <typename T, size_t N>
constexpr auto mod_inv2(big_int<N, T> a, big_int<N, T> modulus) {
  big_int<N, T> t{0};
  big_int<N, T> newt{1};
  auto r = modulus;
  auto newr = a;
  bool t_neg = false, newt_neg = false;


  while (newr != big_int<1, T>{0}) {
    auto qr = div(r, newr);
    auto tmp = t;
    auto tmp2 = partial_mul<N>(qr.quotient, newt);

    if (!t_neg && !newt_neg) {
      newt_neg = tmp2 > tmp;
    } else if (!t_neg && newt_neg) {
      newt_neg = false;
      t_neg = true;
    } else if (t_neg && !newt_neg) {
      newt_neg = true;
      t_neg = false;
    } else {
      newt_neg = tmp2 < tmp;
    }
    t = newt;
    newt = subtract_ignore_carry(tmp, tmp2);
    r = newr;
    newr = qr.remainder;
  }
  // if r > 1 then return "a is not invertible"
  if (t_neg)
    t = add_ignore_carry(t, modulus);
  return t;
}
```

**Comment by niekbouman** [comment]
Indeed! Thank you very much for spotting this.

Fixed in: [commit 53394f92e](https://github.com/niekbouman/ctbignum/commit/53394f92e06557d670b6ce771e6111cc7671ef15)

To avoid tracking signs, I took inspiration from the mpModInv function in David Ireland's "BigDigits" library; essentially to keep track of the parity of the number of iterations, and apply the correction conditionally on this parity.
